### ISSUE TITLE
pkg_resources is deprecated, don't import from there

### ISSUE THREAD

**Issue by Joshix-1** [Isotr0py/pillow-jpegxl-plugin#13]
pkg_resources is deprecated: https://setuptools.pypa.io/en/latest/pkg_resources.html
              and as setuptools isn't guaranteed to be installed, it may not even be there

_Originally posted by @Joshix-1 in https://github.com/Isotr0py/pillow-jpegxl-plugin/pull/12#discussion_r1473404914_

**Comment by Joshix-1** [comment]
You should probably use https://pypi.org/project/packaging/ and their version parsing function: `from packaging.version import parse`

**Comment by Isotr0py** [comment]
I have made a PR to replace `pkg_resources`.
This will be released in the next version.
