### ISSUE TITLE
Python execution fails with undefined symbol: JxlGetDefaultCms

### ISSUE THREAD

**Issue by brunoais** [Isotr0py/pillow-jpegxl-plugin#18]
I'm trying out this project but I'm getting:
```
pillow_jxl/pillow_jxl.cpython-310-x86_64-linux-gnu.so: undefined symbol: JxlGetDefaultCms
```

Just making this issue so you are aware of this. Thank you for making this reality.

**System data:**
* Python 3.10.12
* Using linux 6.5.0 x86_64
* Pillow: 10.2.0
* [v1.1.0pre](https://github.com/Isotr0py/pillow-jpegxl-plugin/releases/tag/v1.1.0pre) (installed using: ` pip install "https://github.com/Isotr0py/pillow-jpegxl-plugin/releases/download/v1.1.0pre/pillow_jxl_plugin-1.1.0-cp310-cp310-manylinux_2_28_x86_64.whl"`)
* libjxl v0.9.1

**Comment by Isotr0py** [comment]
Thanks for reporting this!

It seems that the `build.rs` doesn't link `libjxl` successfully due to the `libjxl` upgrade.

I haven't fully tested the pre-release wheels yet, and there are still some issues to be solved before the `v1.1.0` release.

I will fix them soon.

**Comment by Isotr0py** [comment]
The latest [v1.1.0](https://github.com/Isotr0py/pillow-jpegxl-plugin/releases/tag/v1.1.0) release should fix this.

Please try out the latest release :)

**Comment by brunoais** [comment]
It's fixed. At least, this problem is. Thank you so much for such a fast resolve!
