### ISSUE TITLE
Read/write EXIF data support

### ISSUE THREAD

**Issue by chameroy** [Isotr0py/pillow-jpegxl-plugin#20]
Hello,

I've been experimenting with lossless JXL as a source format for image processing using PIL and OpenCV. Unfortunately, the output files (also in lossless JXL) lack the EXIF data found in the source files and I need to transfer that data. I've been successful in using PIL to transfer EXIF data from TIF to JPG, but I haven't been able to do the same with JXL. I've tried JXL -> JXL and TIF -> JXL, with no luck. It also appears that PIL (using the plugin) is unable to extract EXIF data from lossless JXL files.

Would it be possibly to get this functionality (assuming it doesn't already exist and I'm doing something wrong)? I've also tried ExifTool as a workaround, but no luck there either. Maybe it's a limitation of the format?

Thanks!

**Comment by Isotr0py** [comment]
It seems that jpeg reconstruction can store EXIF data with container:
```python
with Image.open("IMG_20170723_133043.jpg") as img:
    img.save("IMG_20170723_133043-plugin.jxl", lossless=True)
```

And it seems that encoding from png won't keep EXIF data, because libjxl's API disable it by default: [libjxl encoder API](https://libjxl.readthedocs.io/en/latest/api_encoder.html#_CPPv418JxlEncoderUseBoxesP10JxlEncoder)

**Comment by Isotr0py** [comment]
The new [v1.2.0 release](https://github.com/Isotr0py/pillow-jpegxl-plugin/releases/tag/v1.2.0) has supported EXIF data encoding.

Please have a try! :)
