### ISSUE TITLE
[Feature] Expose encoding effort parameter

### ISSUE THREAD

**Issue by jojje** [Isotr0py/pillow-jpegxl-plugin#23]
## What
An encoding parameter for specifying the computational effort to spend during image encoding.

## Why
Allowing the user to specify the trade-off between time waiting to encode and compression ratio.

It seems the hard-coded effort is somewhere between 7-8 which means encoding large images (4K or 8K) is extremely slow.
For reference, a 4K image requires 74s of compute (10s wall clock time) on a Ryzen 7950x, which is a very long time. Being able to drop the effort to 3 would reduce the encoding time by about an order of magnitude, with a very marginal increase in file size at the same visual quality.

Being able to reduce the computational effort is especially important when working with a lot of images, which is one major use case for Pillow.

[From](https://github.com/libjxl/libjxl/blob/bf2b7655db56bdec39fa81b150ccde36e654372a/tools/cjxl_main.cc#L127) `cjxl` reference encoder:
```
 --effort=EFFORT
    Encoder effort setting. Range: 1 .. 9.
    Default: 7. Higher numbers allow more computation at the expense of time.
    For lossless, generally it will produce smaller files.
    For lossy, higher effort should more accurately reach the target quality.
```

For reference, what these effort values map to concretely is a set of flags that enable or disable certain optimizations during the encode process. Here's a [more detailed](https://github.com/libjxl/libjxl/blob/bf2b7655db56bdec39fa81b150ccde36e654372a/lib/jxl/common.h#L36) set of what features are enabled and disabled for each effort profile. Note that the values in the code uses the inverse of the effort parameter, so are calculated as `9 - <effort>`, where for instance effort 7 maps to `9-7 = 2` which is the slow `kKitten` profile, while the much more sane effort of 3 (which imo ought to have been the default effort profile) maps to the well balanced `kCheetah` profile.

## Quantitative data
Here is an example how the effort profile scales compressibility vs encoding speed for a couple of  mixed 4K nature photographs and CGI images.

![image](https://github.com/jojje/gh-images/assets/134889/ec320f82-d0aa-4a40-9958-61c7ca20ec9f)

![jxl-effort-efficiency-small](https://github.com/jojje/gh-images/assets/134889/cb72025e-8576-4aad-a306-262ccc984529)

**Comment by Isotr0py** [comment]
In new v1.1.2 release, you can use `effort` in img saving:
```python
with Image.open("example.png") as img:
    img.save("example.jxl", lossless=True, effort=3)
```

**Comment by jojje** [comment]
Works fantastically. Thank you so much Sun for your quick and attentive work. The plugin is now perfect for my needs 👍
