### ISSUE TITLE
Add support for ICC profiles

### ISSUE THREAD

**Issue by drhead** [Isotr0py/pillow-jpegxl-plugin#31]
It seems that ICC profiles are not returned by the image decoder.  Currently, attempting to load any non-sRGB images through my existing color management pipelines will return different results.  It does seem that the underlying jpegxl-rs library has proper support for passing ICC profile info through its decoder, so could support for that be added so that PIL's ImageCms functions work properly with JXL images?

**Comment by Isotr0py** [comment]
New release should support ICC profile now.
