### ISSUE TITLE
Could you release a new version against version 0.11.1 of jpegxl-rs?

### ISSUE THREAD

**Issue by rphlo** [Isotr0py/pillow-jpegxl-plugin#67]
Current version fail to build on linux ARM CPUs due to a bug in previous version of jpegxl-rs library.
Could you bump jpegxl-rs version and push it to PyPI?

**Comment by Isotr0py** [comment]
[v1.2.8](https://pypi.org/project/pillow-jxl-plugin/1.2.8/#files) has released, does it work on linux ARM CPUs?
